export const properties = [
  {
    id: 1,
    address: "123 Main Street",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 850,
    yearBuilt: 2005,
    rent: 2500,
    deposit: 2500,
    status: "Occupied",
    description: "Modern apartment in the heart of Manhattan with great views.",
    hasParking: true,
    hasPets: false,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 2,
    address: "456 Oak Avenue",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1200,
    yearBuilt: 1998,
    rent: 3200,
    deposit: 3200,
    status: "Vacant",
    description: "Spacious family home with backyard in a quiet neighborhood.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 3,
    address: "789 Pine Street",
    city: "Queens",
    state: "NY",
    zipCode: "11101",
    type: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 650,
    yearBuilt: 2010,
    rent: 1800,
    deposit: 1800,
    status: "Occupied",
    description: "Cozy studio apartment with modern amenities.",
    hasParking: false,
    hasPets: false,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: true,
  },
  {
    id: 4,
    address: "101 Maple Road",
    city: "Bronx",
    state: "NY",
    zipCode: "10451",
    type: "House",
    bedrooms: 4,
    bathrooms: 2.5,
    squareFeet: 1800,
    yearBuilt: 1985,
    rent: 2800,
    deposit: 2800,
    status: "Maintenance",
    description: "Large family home with renovated kitchen and bathrooms.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 5,
    address: "202 Cedar Lane",
    city: "Staten Island",
    state: "NY",
    zipCode: "10301",
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1500,
    yearBuilt: 2000,
    rent: 2600,
    deposit: 2600,
    status: "Occupied",
    description: "Beautiful home with garden and finished basement.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 6,
    address: "303 Birch Blvd",
    city: "New York",
    state: "NY",
    zipCode: "10002",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 900,
    yearBuilt: 2015,
    rent: 2700,
    deposit: 2700,
    status: "Vacant",
    description: "Luxury apartment with doorman and gym access.",
    hasParking: true,
    hasPets: false,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 7,
    address: "404 Elm Street",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11202",
    type: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 700,
    yearBuilt: 2008,
    rent: 2000,
    deposit: 2000,
    status: "Occupied",
    description: "Charming apartment in trendy neighborhood.",
    hasParking: false,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 8,
    address: "505 Willow Way",
    city: "Queens",
    state: "NY",
    zipCode: "11102",
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1400,
    yearBuilt: 1995,
    rent: 2900,
    deposit: 2900,
    status: "Occupied",
    description: "Well-maintained home with recent updates.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 9,
    address: "606 Spruce Street",
    city: "Bronx",
    state: "NY",
    zipCode: "10452",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 800,
    yearBuilt: 2000,
    rent: 1900,
    deposit: 1900,
    status: "Vacant",
    description: "Affordable apartment with good public transportation access.",
    hasParking: false,
    hasPets: false,
    hasAC: false,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 10,
    address: "707 Aspen Avenue",
    city: "Staten Island",
    state: "NY",
    zipCode: "10302",
    type: "House",
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2000,
    yearBuilt: 2010,
    rent: 3500,
    deposit: 3500,
    status: "Occupied",
    description: "Luxury home with modern design and high-end finishes.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 11,
    address: "808 Redwood Road",
    city: "New York",
    state: "NY",
    zipCode: "10003",
    type: "Commercial",
    bedrooms: 0,
    bathrooms: 2,
    squareFeet: 1500,
    yearBuilt: 2005,
    rent: 4500,
    deposit: 4500,
    status: "Vacant",
    description: "Prime retail space in high-traffic area.",
    hasParking: true,
    hasPets: false,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 12,
    address: "909 Sequoia Street",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11203",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1100,
    yearBuilt: 2012,
    rent: 2800,
    deposit: 2800,
    status: "Occupied",
    description: "Family-friendly apartment with playground access.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 13,
    address: "1010 Cypress Circle",
    city: "Queens",
    state: "NY",
    zipCode: "11103",
    type: "House",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 950,
    yearBuilt: 1980,
    rent: 2200,
    deposit: 2200,
    status: "Maintenance",
    description: "Cozy home undergoing kitchen renovation.",
    hasParking: true,
    hasPets: false,
    hasAC: false,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 14,
    address: "1111 Juniper Junction",
    city: "Bronx",
    state: "NY",
    zipCode: "10453",
    type: "Apartment",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 600,
    yearBuilt: 1995,
    rent: 1600,
    deposit: 1600,
    status: "Occupied",
    description: "Affordable apartment with utilities included.",
    hasParking: false,
    hasPets: false,
    hasAC: false,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 15,
    address: "1212 Magnolia Drive",
    city: "Staten Island",
    state: "NY",
    zipCode: "10303",
    type: "House",
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 1700,
    yearBuilt: 2008,
    rent: 3000,
    deposit: 3000,
    status: "Vacant",
    description: "Beautiful home with water views and updated appliances.",
    hasParking: true,
    hasPets: true,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: true,
  },
  {
    id: 16,
    address: "1313 Sycamore Street",
    city: "New York",
    state: "NY",
    zipCode: "10004",
    type: "Commercial",
    bedrooms: 0,
    bathrooms: 1,
    squareFeet: 1200,
    yearBuilt: 2000,
    rent: 4000,
    deposit: 4000,
    status: "Occupied",
    description: "Office space in downtown financial district.",
    hasParking: false,
    hasPets: false,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 17,
    address: "1414 Poplar Place",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11204",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 750,
    yearBuilt: 2005,
    rent: 2100,
    deposit: 2100,
    status: "Occupied",
    description: "Bright apartment with balcony and city views.",
    hasParking: false,
    hasPets: false,
    hasAC: true,
    hasHeating: true,
    hasWasherDryer: false,
    hasDishwasher: true,
  },
  {
    id: 18,
    address: "1515 Walnut Way",
    city: "Queens",
    state: "NY",
    zipCode: "11104",
    type: "Land",
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 5000,
    yearBuilt: 0,
    rent: 1500,
    deposit: 1500,
    status: "Vacant",
    description: "Vacant lot zoned for residential development.",
    hasParking: false,
    hasPets: false,
    hasAC: false,
    hasHeating: false,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
  {
    id: 19,
    address: "1616 Chestnut Court",
    city: "Bronx",
    state: "NY",
    zipCode: "10454",
    type: "House",
    bedrooms: 3,
    bathrooms: 1.5,
    squareFeet: 1300,
    yearBuilt: 1975,
    rent: 2400,
    deposit: 2400,
    status: "Occupied",
    description: "Classic home with character and fenced yard.",
    hasParking: true,
    hasPets: true,
    hasAC: false,
    hasHeating: true,
    hasWasherDryer: true,
    hasDishwasher: false,
  },
  {
    id: 20,
    address: "1717 Hickory Heights",
    city: "Staten Island",
    state: "NY",
    zipCode: "10304",
    type: "Land",
    bedrooms: 0,
    bathrooms: 0,
    squareFeet: 7500,
    yearBuilt: 0,
    rent: 2000,
    deposit: 2000,
    status: "Vacant",
    description: "Large lot with commercial zoning potential.",
    hasParking: false,
    hasPets: false,
    hasAC: false,
    hasHeating: false,
    hasWasherDryer: false,
    hasDishwasher: false,
  },
]

export const tenants = [
  {
    id: 1,
    firstName: "John",
    lastName: "Smith",
    email: "john.smith@example.com",
    phone: "212-555-1234",
    propertyId: 1,
    leaseStart: "2023-01-01",
    leaseEnd: "2024-01-01",
    rentAmount: 2500,
    securityDeposit: 2500,
    paymentStatus: "Current",
  },
  {
    id: 2,
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily.johnson@example.com",
    phone: "718-555-2345",
    propertyId: 3,
    leaseStart: "2023-03-15",
    leaseEnd: "2024-03-15",
    rentAmount: 1800,
    securityDeposit: 1800,
    paymentStatus: "Current",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Williams",
    email: "michael.williams@example.com",
    phone: "347-555-3456",
    propertyId: 5,
    leaseStart: "2023-02-01",
    leaseEnd: "2024-02-01",
    rentAmount: 2600,
    securityDeposit: 2600,
    paymentStatus: "Late",
  },
  {
    id: 4,
    firstName: "Jessica",
    lastName: "Brown",
    email: "jessica.brown@example.com",
    phone: "646-555-4567",
    propertyId: 7,
    leaseStart: "2023-04-01",
    leaseEnd: "2024-04-01",
    rentAmount: 2000,
    securityDeposit: 2000,
    paymentStatus: "Current",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Jones",
    email: "david.jones@example.com",
    phone: "917-555-5678",
    propertyId: 8,
    leaseStart: "2023-01-15",
    leaseEnd: "2024-01-15",
    rentAmount: 2900,
    securityDeposit: 2900,
    paymentStatus: "Current",
  },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Miller",
    email: "sarah.miller@example.com",
    phone: "212-555-6789",
    propertyId: 10,
    leaseStart: "2023-05-01",
    leaseEnd: "2024-05-01",
    rentAmount: 3500,
    securityDeposit: 3500,
    paymentStatus: "Current",
  },
  {
    id: 7,
    firstName: "Robert",
    lastName: "Davis",
    email: "robert.davis@example.com",
    phone: "718-555-7890",
    propertyId: 12,
    leaseStart: "2023-03-01",
    leaseEnd: "2024-03-01",
    rentAmount: 2800,
    securityDeposit: 2800,
    paymentStatus: "Current",
  },
  {
    id: 8,
    firstName: "Jennifer",
    lastName: "Garcia",
    email: "jennifer.garcia@example.com",
    phone: "347-555-8901",
    propertyId: 14,
    leaseStart: "2023-02-15",
    leaseEnd: "2024-02-15",
    rentAmount: 1600,
    securityDeposit: 1600,
    paymentStatus: "Late",
  },
  {
    id: 9,
    firstName: "Christopher",
    lastName: "Rodriguez",
    email: "christopher.rodriguez@example.com",
    phone: "646-555-9012",
    propertyId: 16,
    leaseStart: "2023-06-01",
    leaseEnd: "2024-06-01",
    rentAmount: 4000,
    securityDeposit: 4000,
    paymentStatus: "Current",
  },
  {
    id: 10,
    firstName: "Amanda",
    lastName: "Wilson",
    email: "amanda.wilson@example.com",
    phone: "917-555-0123",
    propertyId: 17,
    leaseStart: "2023-04-15",
    leaseEnd: "2024-04-15",
    rentAmount: 2100,
    securityDeposit: 2100,
    paymentStatus: "Current",
  },
  {
    id: 11,
    firstName: "Matthew",
    lastName: "Martinez",
    email: "matthew.martinez@example.com",
    phone: "212-555-1357",
    propertyId: 19,
    leaseStart: "2023-01-01",
    leaseEnd: "2024-01-01",
    rentAmount: 2400,
    securityDeposit: 2400,
    paymentStatus: "Current",
  },
  {
    id: 12,
    firstName: "Ashley",
    lastName: "Anderson",
    email: "ashley.anderson@example.com",
    phone: "718-555-2468",
    propertyId: 1,
    leaseStart: "2023-07-01",
    leaseEnd: "2024-07-01",
    rentAmount: 2500,
    securityDeposit: 2500,
    paymentStatus: "Current",
  },
  {
    id: 13,
    firstName: "Joshua",
    lastName: "Taylor",
    email: "joshua.taylor@example.com",
    phone: "347-555-3579",
    propertyId: 3,
    leaseStart: "2023-05-15",
    leaseEnd: "2024-05-15",
    rentAmount: 1800,
    securityDeposit: 1800,
    paymentStatus: "Late",
  },
  {
    id: 14,
    firstName: "Megan",
    lastName: "Thomas",
    email: "megan.thomas@example.com",
    phone: "646-555-4680",
    propertyId: 5,
    leaseStart: "2023-08-01",
    leaseEnd: "2024-08-01",
    rentAmount: 2600,
    securityDeposit: 2600,
    paymentStatus: "Current",
  },
  {
    id: 15,
    firstName: "Andrew",
    lastName: "Jackson",
    email: "andrew.jackson@example.com",
    phone: "917-555-5791",
    propertyId: 7,
    leaseStart: "2023-06-15",
    leaseEnd: "2024-06-15",
    rentAmount: 2000,
    securityDeposit: 2000,
    paymentStatus: "Current",
  },
  {
    id: 16,
    firstName: "Stephanie",
    lastName: "White",
    email: "stephanie.white@example.com",
    phone: "212-555-6802",
    propertyId: 8,
    leaseStart: "2023-03-01",
    leaseEnd: "2024-03-01",
    rentAmount: 2900,
    securityDeposit: 2900,
    paymentStatus: "Current",
  },
  {
    id: 17,
    firstName: "Kevin",
    lastName: "Harris",
    email: "kevin.harris@example.com",
    phone: "718-555-7913",
    propertyId: 10,
    leaseStart: "2023-07-15",
    leaseEnd: "2024-07-15",
    rentAmount: 3500,
    securityDeposit: 3500,
    paymentStatus: "Current",
  },
  {
    id: 18,
    firstName: "Nicole",
    lastName: "Martin",
    email: "nicole.martin@example.com",
    phone: "347-555-8024",
    propertyId: 12,
    leaseStart: "2023-04-01",
    leaseEnd: "2024-04-01",
    rentAmount: 2800,
    securityDeposit: 2800,
    paymentStatus: "Late",
  },
  {
    id: 19,
    firstName: "Ryan",
    lastName: "Thompson",
    email: "ryan.thompson@example.com",
    phone: "646-555-9135",
    propertyId: 14,
    leaseStart: "2023-08-15",
    leaseEnd: "2024-08-15",
    rentAmount: 1600,
    securityDeposit: 1600,
    paymentStatus: "Current",
  },
  {
    id: 20,
    firstName: "Lauren",
    lastName: "Garcia",
    email: "lauren.garcia@example.com",
    phone: "917-555-0246",
    propertyId: 16,
    leaseStart: "2023-05-01",
    leaseEnd: "2024-05-01",
    rentAmount: 4000,
    securityDeposit: 4000,
    paymentStatus: "Current",
  },
]

export const maintenanceRequests = [
  {
    id: 1,
    propertyId: 1,
    tenantId: 1,
    title: "Leaky Faucet",
    description: "Kitchen faucet is dripping constantly",
    priority: "Medium",
    status: "Open",
    dateCreated: "2023-11-01",
    dateCompleted: null,
    assignedTo: "John's Plumbing",
    cost: 0,
  },
  {
    id: 2,
    propertyId: 3,
    tenantId: 2,
    title: "Broken Window",
    description: "Living room window won't close properly",
    priority: "High",
    status: "In Progress",
    dateCreated: "2023-11-02",
    dateCompleted: null,
    assignedTo: "ABC Glass Repair",
    cost: 250,
  },
  {
    id: 3,
    propertyId: 5,
    tenantId: 3,
    title: "HVAC Not Working",
    description: "Heating system not producing warm air",
    priority: "High",
    status: "Open",
    dateCreated: "2023-11-03",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 4,
    propertyId: 7,
    tenantId: 4,
    title: "Clogged Drain",
    description: "Bathroom sink drains very slowly",
    priority: "Low",
    status: "Completed",
    dateCreated: "2023-10-28",
    dateCompleted: "2023-10-30",
    assignedTo: "Quick Fix Plumbing",
    cost: 85,
  },
  {
    id: 5,
    propertyId: 8,
    tenantId: 5,
    title: "Electrical Outlet",
    description: "Kitchen outlet not working",
    priority: "Medium",
    status: "In Progress",
    dateCreated: "2023-11-04",
    dateCompleted: null,
    assignedTo: "City Electric",
    cost: 150,
  },
  {
    id: 6,
    propertyId: 10,
    tenantId: 6,
    title: "Garage Door",
    description: "Garage door opener remote not working",
    priority: "Low",
    status: "Open",
    dateCreated: "2023-11-05",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 7,
    propertyId: 12,
    tenantId: 7,
    title: "Water Pressure",
    description: "Low water pressure in shower",
    priority: "Medium",
    status: "Completed",
    dateCreated: "2023-10-25",
    dateCompleted: "2023-10-27",
    assignedTo: "Metro Plumbing",
    cost: 120,
  },
  {
    id: 8,
    propertyId: 14,
    tenantId: 8,
    title: "Smoke Detector",
    description: "Smoke detector beeping - needs battery",
    priority: "High",
    status: "Completed",
    dateCreated: "2023-10-30",
    dateCompleted: "2023-10-30",
    assignedTo: "Self-Service",
    cost: 15,
  },
  {
    id: 9,
    propertyId: 16,
    tenantId: 9,
    title: "Air Conditioning",
    description: "AC unit making loud noise",
    priority: "Medium",
    status: "Open",
    dateCreated: "2023-11-06",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 10,
    propertyId: 17,
    tenantId: 10,
    title: "Cabinet Door",
    description: "Kitchen cabinet door hinge broken",
    priority: "Low",
    status: "In Progress",
    dateCreated: "2023-11-07",
    dateCompleted: null,
    assignedTo: "Handy Helper Services",
    cost: 45,
  },
  {
    id: 11,
    propertyId: 19,
    tenantId: 11,
    title: "Toilet Running",
    description: "Toilet keeps running after flush",
    priority: "Medium",
    status: "Open",
    dateCreated: "2023-11-08",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 12,
    propertyId: 1,
    tenantId: 12,
    title: "Light Fixture",
    description: "Dining room light flickering",
    priority: "Low",
    status: "Completed",
    dateCreated: "2023-10-20",
    dateCompleted: "2023-10-22",
    assignedTo: "Bright Electric",
    cost: 75,
  },
  {
    id: 13,
    propertyId: 3,
    tenantId: 13,
    title: "Dishwasher Leak",
    description: "Water pooling under dishwasher",
    priority: "High",
    status: "In Progress",
    dateCreated: "2023-11-09",
    dateCompleted: null,
    assignedTo: "Appliance Repair Pro",
    cost: 200,
  },
  {
    id: 14,
    propertyId: 5,
    tenantId: 14,
    title: "Door Lock",
    description: "Front door lock sticking",
    priority: "Medium",
    status: "Open",
    dateCreated: "2023-11-10",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 15,
    propertyId: 7,
    tenantId: 15,
    title: "Ceiling Fan",
    description: "Bedroom ceiling fan wobbling",
    priority: "Low",
    status: "Completed",
    dateCreated: "2023-10-15",
    dateCompleted: "2023-10-18",
    assignedTo: "Fan Fix Services",
    cost: 60,
  },
  {
    id: 16,
    propertyId: 8,
    tenantId: 16,
    title: "Garbage Disposal",
    description: "Kitchen garbage disposal jammed",
    priority: "Medium",
    status: "Open",
    dateCreated: "2023-11-11",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 17,
    propertyId: 10,
    tenantId: 17,
    title: "Thermostat",
    description: "Thermostat display not working",
    priority: "Medium",
    status: "In Progress",
    dateCreated: "2023-11-12",
    dateCompleted: null,
    assignedTo: "Climate Control Co",
    cost: 180,
  },
  {
    id: 18,
    propertyId: 12,
    tenantId: 18,
    title: "Washing Machine",
    description: "Washing machine not draining",
    priority: "High",
    status: "Open",
    dateCreated: "2023-11-13",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
  {
    id: 19,
    propertyId: 14,
    tenantId: 19,
    title: "Window Screen",
    description: "Bedroom window screen torn",
    priority: "Low",
    status: "Completed",
    dateCreated: "2023-10-10",
    dateCompleted: "2023-10-12",
    assignedTo: "Screen Repair Plus",
    cost: 35,
  },
  {
    id: 20,
    propertyId: 16,
    tenantId: 20,
    title: "Parking Lot Light",
    description: "Parking lot security light out",
    priority: "Medium",
    status: "Open",
    dateCreated: "2023-11-14",
    dateCompleted: null,
    assignedTo: null,
    cost: 0,
  },
]
